[package]
name = "lab_1"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
winapi = { version = "0.3.9", features = ["wingdi", "winuser", "libloaderapi", "combaseapi", "objbase", "shobjidl", "winerror", "mmeapi", "mmsystem", "windef"] }
winapi-util = "0.1.5"
#winapi-x86_64-pc-windows-gnu = "0.4.0"
[target.'cfg(target_os = "windows")'.features]
default = ["windows"]
[build-dependencies]
embed-resource = "2.3.0"
